# DigitalOcean App Platform Configuration
# This file defines how the Portfolio Events API should be deployed on DigitalOcean App Platform

name: portfolio-events-api

# Service configuration for the NestJS application
services:
  - name: api
    # GitHub repository configuration
    github:
      repo: vedaterenoglu/portfolio-events-rest-api
      branch: main
      deploy_on_push: true
    
    # Build configuration
    build_command: npm run build
    
    # Runtime configuration
    run_command: npm run start:prod
    
    # Environment configuration
    environment_slug: node-js
    instance_size_slug: basic-xxs  # $5/month - suitable for portfolio demo
    instance_count: 1
    
    # HTTP configuration
    http_port: 8080
    
    # Health check configuration
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 10
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3
    
    # Source directory
    source_dir: /
    
    # Environment variables (will be set in App Platform dashboard)
    envs:
      - key: NODE_ENV
        value: production
        type: GENERAL
      - key: PORT
        value: "8080"
        type: GENERAL
      - key: DATABASE_URL
        value: "${DATABASE_URL}"
        type: SECRET
      - key: CLERK_PUBLISHABLE_KEY
        value: "${CLERK_PUBLISHABLE_KEY}"
        type: GENERAL
      - key: CLERK_SECRET_KEY
        value: "${CLERK_SECRET_KEY}"
        type: SECRET
      - key: STRIPE_SECRET_KEY
        value: "${STRIPE_SECRET_KEY}"
        type: SECRET
      - key: CORS_ORIGIN
        value: "${CORS_ORIGIN}"
        type: GENERAL
      - key: CORS_CREDENTIALS
        value: "true"
        type: GENERAL

# Region configuration
region: fra  # Frankfurt - closest to EU-Central-1 where Neon DB is hosted

# Alerts configuration (optional)
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED